### ISSUE TITLE
update possible groupName arguments for management_addMemberToBuiltInSecurityGroup()

### ISSUE THREAD

**Issue by nhung617** [IronBox/ironboxdx-python#2]
Hi,

Would it be possible to add 'SseContainerServiceReader' and 'SseContainerServiceCreator' as acceptable groupName values when calling management_addMemberToBuiltInSecurityGroup()?

We're currently getting users' roles via management_readOrganizationMemberEntityMetadata() so it would be nice to be able to use those same values we get back when adding users to groups. 

Thank you!

**Comment by kevinjameslam** [comment]
Not a problem, can do and this is an easy add.

Since we're at Thursday already, I doubt this will make it passed the test suites in time for a production push this weekend, but next weekend is a definite possibility. 

Thanks,

Kevin

**Comment by nhung617** [comment]
Hi Kevin,

Sounds good; no worries, it's not a terribly urgent issue. Thanks for the quick response! :)

**Comment by kevinjameslam** [comment]
Okay this is done and making its way through the test passes. You'll be able to specify "SseContainerServiceCreator" and "SseContainerServiceReader" when you're adding/removing/reading built-in security groups via the management REST API.

Should be live by next weekend, will update this thread when that happens.

Thanks,

Kevin

**Comment by kevinjameslam** [comment]
Production environment updated, and sample scripts updated so you should be able to specify security groups by the alternative IDs now "SseContainerServiceCreator" and "SseContainerServiceReader".

Thanks,

Kevin

**Comment by nhung617** [comment]
Awesome, thanks very much Kevin! :)

Nicholas
